# Generated by Django 5.1.5 on 2025-02-08 13:07
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("der_die_das", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type_entry",
            name="type_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
